### ISSUE TITLE
能否发布到 Store 安装使用？

### ISSUE THREAD

**Issue by lijialiang** [JoysKang/open-history-item#1]
如果发布到 Store 安装使用的话，通过同步可以在多台设备上使用，不需要每个设备上都 clone 下来安装。

**Comment by JoysKang** [comment]
长时间没有维护了，如果想发布需要切换的最新的 raycast/api。
最新的和当前使用的版本不兼容，暂时没有打算去升级。
如果你想发布可以 fork 一份去修改发布。
